#!/bin/bash
#
test x"$REDIS_DEBUG" != x && set -x
REDIS_CLI=/usr/bin/redis-cli
CONFIG_FILE="/etc/redis/redis.conf"
HOST=`awk '/^[[:blank:]]*bind/ { print $2 }' $CONFIG_FILE`
PORT=`awk '/^[[:blank:]]*port/ { print $2 }' $CONFIG_FILE`
AUTH=`awk '/^[[:blank:]]*requirepass/ { print $2 }' $CONFIG_FILE`
echo -e "Host: $HOST\nPort: $PORT"
$REDIS_CLI -h $HOST -p $PORT -a $AUTH shutdown

