name: [DEV] Add Packages

on: 
  workflow_dispatch:
    inputs:
      package_url:
        description: 'Package URLs'     
        required: true
        default: ''
jobs:
  add_packages:
    runs-on: self-hosted
    name: add-packages
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        
      - name: Download New RPM
        env:
          URL_LIST: ${{ github.event.inputs.package_url }}
        run: |
          echo $URL_LIST | xargs -n 1 -P 8 wget -P dev/7/os/x86_64/Packages -q
          createrepo --update dev/7/os/x86_64
        
      - name: Update Repository
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update DEV Repository
          file_pattern: dev/7/os/x86_64/*
          commit_user_name: RDMX87
          commit_user_email: RDMX87@motorolasolutions.com
          commit_author: RDMX87 <RDMX87@motorolasolutions.com>
          disable_globbing: false
