name: Run Updater

on: 
  workflow_dispatch:
    inputs:
      package_url:
        description: 'Package URL'     
        required: true
        default: ''
jobs:
  updater:
    runs-on: self-hosted
    name: updater-1
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        
      - name: Download New RPM
        run: |
          wget -P 7/os/x86_64/Packages ${{ github.event.inputs.package_url }}
          createrepo --update 7/os/x86_64
        
      - name: Update Repository
      - uses: EndBug/add-and-commit@v7
        with:
          add: '7/os/x86_64'
          author_name: RDMX87
          author_email: RDMX87@motorolasolutions.com
          message: 'Update Repository'
          push: true
