name: [DEV] Update Repo

on:
  workflow_dispatch
  #schedule:
  #  - cron:  '0 0 * * *'

jobs:
  update_repo:
    runs-on: self-hosted
    name: update-repo
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        
      - name: Check RPM updates
        run: sudo bash -x dev/update-repo.sh
        
      - name: Update Repository
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update DEV Repository
          file_pattern: dev/7/os/x86_64/*
          commit_user_name: RDMX87
          commit_user_email: RDMX87@motorolasolutions.com
          commit_author: RDMX87 <RDMX87@motorolasolutions.com>
          disable_globbing: false
